# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microwave < Formula
  desc "Command-line interface for the Microwave API"
  homepage "https://microwave.sh"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.5.0/microwave_1.5.0_darwin_amd64.tar.gz"
      sha256 "e9fa8fc9c80f01e0a099e107c1481e276d9274c973685cc5ee7d9969e19dd9e6"

      define_method(:install) do
        bin.install "microwave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.5.0/microwave_1.5.0_darwin_arm64.tar.gz"
      sha256 "c3f172fcc244bc721afd052379e2681dd3aed5eaccef58642efac3e076b6cd81"

      define_method(:install) do
        bin.install "microwave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.5.0/microwave_1.5.0_linux_amd64.tar.gz"
      sha256 "f3c3b7f23818ca81e0baf9a10ee21e17be1613c482a5f3ccfe367dbc84721ef6"
      define_method(:install) do
        bin.install "microwave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.5.0/microwave_1.5.0_linux_arm64.tar.gz"
      sha256 "2da483dd2107a72bc51313d9fad1c72cf84782f436deb8af3e58678eab62e957"
      define_method(:install) do
        bin.install "microwave"
      end
    end
  end
end
