# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microwave < Formula
  desc "Command-line interface for the Microwave API"
  homepage "https://microwave.sh"
  version "1.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.7.3/microwave_1.7.3_darwin_amd64.tar.gz"
      sha256 "2efad20ea44f46ecd40f2f202e86b8f0c7585e0a8b2b12a351dd8e8edf33b428"

      define_method(:install) do
        bin.install "microwave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.7.3/microwave_1.7.3_darwin_arm64.tar.gz"
      sha256 "1cd4ddb03b71a79901e87be1a4665d0cda43151ed5c3f588a0fdcc6f0db29f36"

      define_method(:install) do
        bin.install "microwave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.7.3/microwave_1.7.3_linux_amd64.tar.gz"
      sha256 "d9282e97279229d08c7007e7fefe378b52bb7b02c7a7a1ea41e3373af72c75c9"
      define_method(:install) do
        bin.install "microwave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/microwave-sh/microwave-cli/releases/download/v1.7.3/microwave_1.7.3_linux_arm64.tar.gz"
      sha256 "f2f9f3eb5b2d17498751d0912ec30453a9e578c065d13b64a0bf8c96f5f7f021"
      define_method(:install) do
        bin.install "microwave"
      end
    end
  end
end
